[tool.poetry]
name = "master-thesis-demo"
version = "0.1.0"
description = ""
authors = ["Marcin Seliga"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "<4.0,>=3.13"
ipykernel = ">=6.30.1,<7.0.0"
pandas = "^2.3.2"
matplotlib = "^3.10.6"
scipy = "^1.16.2"
plotly = "^6.3.0"
nbformat = "^5.10.4"
dotenv = "^0.9.9"
py2neo = "^2021.2.4"
networkx = "^3.5"
openai = "^2.1.0"
langchain = "^0.3.27"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
